In [ ]:
import pyspark
import pandas as pd

In [ ]:
df=pd.read_csv('/content/test1.csv')
df.head() #five # if i want 1st 5 data

       Name  age  Experience  Salary
0       Ben   31          10   30000
1  Srikanth   30           8   25000
2     Sunny   29           4   20000
3      Paul   24           3   20000
4    Harish   21           1   15000

In [ ]:
# how to check row and column
df.shape

(6, 4)

In [ ]:
df.head(2) # 1st two data

       Name  age  Experience  Salary
0       Ben   31          10   30000
1  Srikanth   30           8   25000

In [ ]:
df.head(5)

       Name  age  Experience  Salary
0       Ben   31          10   30000
1  Srikanth   30           8   25000
2     Sunny   29           4   20000
3      Paul   24           3   20000
4    Harish   21           1   15000

In [ ]:
df.tail() # last data

       Name  age  Experience  Salary
1  Srikanth   30           8   25000
2     Sunny   29           4   20000
3      Paul   24           3   20000
4    Harish   21           1   15000
5     Shiva   23           2   18000

In [ ]:
df.tail(2) # last two data

     Name  age  Experience  Salary
4  Harish   21           1   15000
5   Shiva   23           2   18000

In [ ]:
df.info() # to find the null value # 6 non-null is no null value

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   age         6 non-null      int64
 2   Experience  6 non-null      int64
 3   Salary      6 non-null      int64
dtypes: int64(3), object(1)
memory usage: 324.0+ bytes

In [ ]:
df.isnull().sum() # to check a null value yes are no # there is zero means no null value

Name          0
age           0
Experience    0
Salary        0
dtype: int64

In [ ]:
from pyspark.sql import SparkSession

In [ ]:
spark=SparkSession.builder.appName('Demo').getOrCreate()

In [ ]:
spark

In [ ]:
df=spark.read.csv('/content/test1.csv')
df.show(2)

+----+---+----------+------+
| _c0|_c1|       _c2|   _c3|
+----+---+----------+------+
|Name|age|Experience|Salary|
| Ben| 31|        10| 30000|
+----+---+----------+------+
only showing top 2 rows

In [ ]:
df.show()

+--------+---+----------+------+
|     _c0|_c1|       _c2|   _c3|
+--------+---+----------+------+
|    Name|age|Experience|Salary|
|     Ben| 31|        10| 30000|
|Srikanth| 30|         8| 25000|
|   Sunny| 29|         4| 20000|
|    Paul| 24|         3| 20000|
|  Harish| 21|         1| 15000|
|   Shiva| 23|         2| 18000|
+--------+---+----------+------+

In [ ]:
df=spark.read.option('header','true').csv('test1.csv')

In [ ]:
df.show(3)

+--------+---+----------+------+
|    Name|age|Experience|Salary|
+--------+---+----------+------+
|     Ben| 31|        10| 30000|
|Srikanth| 30|         8| 25000|
|   Sunny| 29|         4| 20000|
+--------+---+----------+------+
only showing top 3 rows

In [ ]:
df.printSchema()

root
 |-- Name: string (nullable = true)
 |-- age: string (nullable = true)
 |-- Experience: string (nullable = true)
 |-- Salary: string (nullable = true)

In [ ]:
df.head(5)

[Row(Name='Ben', age='31', Experience='10', Salary='30000'),
 Row(Name='Srikanth', age='30', Experience='8', Salary='25000'),
 Row(Name='Sunny', age='29', Experience='4', Salary='20000'),
 Row(Name='Paul', age='24', Experience='3', Salary='20000'),
 Row(Name='Harish', age='21', Experience='1', Salary='15000')]

In [ ]:
df=spark.read.csv("/content/test1.csv",header=True,inferSchema=True)

In [ ]:
df.printSchema()

root
 |-- Name: string (nullable = true)
 |-- age: integer (nullable = true)
 |-- Experience: integer (nullable = true)
 |-- Salary: integer (nullable = true)

In [ ]:
df.head()

Row(Name='Ben', age=31, Experience=10, Salary=30000)

In [ ]:
# selecting single column
df.select('Name').show()

+--------+
|    Name|
+--------+
|     Ben|
|Srikanth|
|   Sunny|
|    Paul|
|  Harish|
|   Shiva|
+--------+

In [ ]:
df.select('Name').show(2)

+--------+
|    Name|
+--------+
|     Ben|
|Srikanth|
+--------+
only showing top 2 rows

In [ ]:
df.select('Name','Experience').show()

+--------+----------+
|    Name|Experience|
+--------+----------+
|     Ben|        10|
|Srikanth|         8|
|   Sunny|         4|
|    Paul|         3|
|  Harish|         1|
|   Shiva|         2|
+--------+----------+

In [ ]:
df.filter(df['Name']=='Ben').show()

+----+---+----------+------+
|Name|age|Experience|Salary|
+----+---+----------+------+
| Ben| 31|        10| 30000|
+----+---+----------+------+

In [ ]:
df.filter(df['Experience']==1).show()

+------+---+----------+------+
|  Name|age|Experience|Salary|
+------+---+----------+------+
|Harish| 21|         1| 15000|
+------+---+----------+------+

In [ ]:
df.dtypes

[('Name', 'string'), ('age', 'int'), ('Experience', 'int'), ('Salary', 'int')]

In [ ]:
df.describe().show()

+-------+-----+------------------+-----------------+------------------+
|summary| Name|               age|       Experience|            Salary|
+-------+-----+------------------+-----------------+------------------+
|  count|    6|                 6|                6|                 6|
|   mean| NULL|26.333333333333332|4.666666666666667|21333.333333333332|
| stddev| NULL| 4.179314138308661|3.559026084010437| 5354.126134736337|
|    min|  Ben|                21|                1|             15000|
|    max|Sunny|                31|               10|             30000|
+-------+-----+------------------+-----------------+------------------+

In [ ]:
ord('B')

66

In [ ]:
print(ord('S'))

83

In [ ]:
print(ord('P'))

80

In [ ]:
print(ord('H'))

72

In [ ]:
print(ord('u'))

117

In [ ]:
print(ord('r'))

114

In [ ]:
print(ord('a'))

97

In [ ]:
print(ord('h'))

104